title: Dmitri's Recipe Site
description: A website with a blog
footer_text: Copyright 2021 Dmitri Tremblay
header_feature_image: ../uploads/gabriel-gurrola-fcgprzmtm5w-unsplash.jpg
header_text: Home Page
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/edgar-castrejon-1csavdwfiew-unsplash.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
